Repository saranghein/Vue.js-Project-Skeleton_Front, pull requests merged in 2025-04, with the labels that each got.

#24 feat: 꺾은선 그래프 생성
  package-lock.json
  package.json
  src/components/Chart.vue
  src/pages/Home.vue
Labels: ⭐ [FEAT], 🍊 경한

#26 Style/#4 header UI
  index.html
  src/components/common/Header.vue
  src/components/common/HomeHeader.vue
  src/pages/Mypage.vue
  src/router/index.js
Labels: ⭐ [FEAT], 💟 [STYLE], 🍋 지민

#27 feat: 배지 공통 컴포넌트 ui 구현
  src/components/common/Badge.vue
  src/pages/Mypage.vue
  src/util/constants.js
Labels: 💟 [STYLE], 🍋 지민

#28 [STYLE/#2] : 거래 내역 리스트(하단부) UI 구현
  src/components/transactionHistory/TransactionItem.vue
  src/components/transactionHistory/TransactionList.vue
  src/components/transactionHistory/formatDate.js
  src/pages/TransactionHistory/TranscationHistory.vue
Labels: 💟 [STYLE], 🍇 소현

#30 Style#9 button UI
  src/components/common/Button.vue
  src/pages/Mypage.vue
Labels: 💟 [STYLE], 🍋 지민

#31 Feat/#12 원형그래프 UI
  db.json
  src/App.vue
  src/assets/fonts.css
  src/components/DoughnutChart.vue
  src/main.js
  src/pages/Home.vue
  src/router/index.js
Labels: ⭐ [FEAT], 🍊 경한

#33 [STYLE/#6] : 거래 내역 상단부 UI
  src/components/transactionHistory/TransactionItem.vue
  src/components/transactionHistory/TransactionList.vue
  src/pages/TransactionHistory/TranscationHistory.vue
  src/util/constants.js
  src/util/formatDate.js
Labels: 💟 [STYLE], 🍇 소현

#35 Feat/#10 sidebar
  src/components/common/Common.vue
  src/components/common/Header.vue
  src/components/common/HomeHeader.vue
  src/components/common/Sidebar.vue
  src/pages/Mypage.vue
  src/router/index.js
Labels: ⭐ [FEAT], 💟 [STYLE], 🍋 지민

#22 chore: github actions 설정
  .github/workflows/deploy.yml
  .github/workflows/lighthouse.yml
  .github/workflows/preview.yml
  .gitignore
  build.sh
  lighthouse.js
  lighthouserc-desktop.cjs
  lighthouserc-mobile.cjs
  package.json
  vite.config.js
Labels: 🍋 지민, 🛠️ [CHORE]

#36 feat: Bottom Modal 컴포넌트
  .github/workflows/preview.yml
  src/components/transactionHistory/BottomModal.vue
  src/util/constants.js
  vercel.json
  vite.config.js
Labels: ⭐ [FEAT], 💟 [STYLE], 🍋 지민

#38 Feat/#23 거래등록페이지 UI
  src/pages/Registration.vue
Labels: ⭐ [FEAT], 🍑 해인

#43 [STYLE/#37] : 거래내역 바텀 모달
  src/components/transactionHistory/FilterBottomModal.vue
  src/components/transactionHistory/TransactionItem.vue
  src/components/transactionHistory/TransactionList.vue
  src/pages/TransactionHistory.vue
  src/router/index.js
Labels: 💟 [STYLE], 🍇 소현

#42 Style/#16 mypage UI
  .github/workflows/pr-preview-github-pages.yml
  .github/workflows/pr-preview-vercel.yml
  src/assets/barcode.png
  src/components/common/Badge.vue
  src/components/common/Button.vue
  src/components/common/Header.vue
  src/components/common/HomeHeader.vue
  src/components/common/Sidebar.vue
  src/components/mypage/InfoItem.vue
  src/pages/Mypage.vue
  vite.config.js
Labels: 💟 [STYLE], 🍋 지민,  ♻️ [REFACTOR]

#46 feat: 반응형 와이드 뷰 추가
  src/components/common/HomeHeader.vue
  src/pages/Home.vue
Labels: ⭐ [FEAT], 🍊 경한, 💟 [STYLE]

#47 feat:카테고리 선택 및 유효성 검사 추가
  db.json
  src/assets/main.css
  src/components/Registration/DropdownSelector.vue
  src/pages/Registration.vue
Labels: ⭐ [FEAT], 🍑 해인

#49 feat: 카테고리 아이콘 컴포넌트
  src/components/common/CategoryIcon.vue
Labels: 💟 [STYLE], 🍋 지민

#50 [Feat/#17] : api service 기본 구조 세팅, 거래내역 get 연결
  src/components/transactionHistory/TransactionList.vue
  src/pages/TransactionHistory.vue
  src/util/apiService.js
  src/util/constants.js
  vite.config.js
Labels: ⭐ [FEAT], 🍇 소현

#54 [Feat/#51] : 거래내역 delete, ui 수정
  src/components/transactionHistory/BottomModal.vue
  src/components/transactionHistory/TransactionList.vue
  src/pages/TransactionHistory.vue
  src/util/apiService.js
  src/util/constants.js
Labels: ⭐ [FEAT], 🍇 소현

#55 feat:post기능추가
  db.json
  src/api/RegisterService.js
  src/components/Registration/CategorySelector.vue
  src/components/Registration/DropdownSelector.vue
  src/components/Registration/MemoInput.vue
  src/components/Registration/PaymentMethodSelector.vue
  src/components/common/Button.vue
  src/pages/Registration.vue
Labels: ⭐ [FEAT], 🍑 해인

#58 [Feat/#57] : 거래내역 필터링 로직, 데스크탑 뷰
  src/components/transactionHistory/EmptyView.vue
  src/components/transactionHistory/FilterBottomModal.vue
  src/components/transactionHistory/TransactionItem.vue
  src/components/transactionHistory/TransactionList.vue
  src/components/transactionHistory/TransactionSummary.vue
  src/pages/TransactionHistory.vue
Labels: ⭐ [FEAT], 🍇 소현

#59 Feat/#18 mypage edit
  src/components/mypageEdit/BirthdayInput.vue
  src/components/mypageEdit/EmailInput.vue
  src/components/mypageEdit/PhoneNumberInput.vue
  src/components/mypageEdit/ProfileImgInput.vue
  src/components/mypageEdit/UsernameInput.vue
  src/pages/Mypage.vue
  src/pages/MypageEdit.vue
  src/router/index.js
  src/stores/useUserStore.js
  src/util/apiService.js
Labels: ⭐ [FEAT], 🍋 지민

#60 Feat/#15 put api기능 api
  db.json
  src/components/Registration/AmountInput.vue
  src/components/Registration/CategorySelector.vue
  src/components/Registration/MemoInput.vue
  src/components/Registration/PaymentMethodSelector.vue
  src/components/Registration/SourceInput.vue
  src/pages/Registration.vue
  src/router/index.js
Labels: ⭐ [FEAT], 🍑 해인

#61 Feat/ Registration 오버레이 작업 및 UI수정
  src/assets/logo1.png
  src/components/Calendar.vue
  src/components/RegistrationModal.vue
  src/components/common/HomeHeader.vue
  src/components/common/Sidebar.vue
  src/pages/Home.vue
Labels: ⭐ [FEAT], 🍊 경한, 💟 [STYLE],  ♻️ [REFACTOR]

#62 Feat 임시브랜치
  db.json
  src/assets/user_img/gallery07.png
  src/components/Chart.vue
  src/components/DoughnutChart.vue
  src/components/common/CategoryIcon.vue
  src/pages/Home.vue
Labels: ⭐ [FEAT], 🍊 경한, 💟 [STYLE], 📝 [TEST], 🔨 [FIX],  ♻️ [REFACTOR]

#63 chore:기타수정사항
  db.json
  src/components/Registration/DateInput.vue
  src/components/Registration/ModalMessage.vue
  src/components/Registration/RegistrationButton.vue
  src/pages/Registration.vue
  src/util/constants.js
Labels: 🛠️ [CHORE], 🍑 해인

#64 [REFACTOR/#20] : 거래내역 UI 수정, 주석
  src/components/transactionHistory/FilterBottomModal.vue
  src/components/transactionHistory/TransactionItem.vue
  src/components/transactionHistory/TransactionList.vue
  src/pages/TransactionHistory.vue
Labels: 🍇 소현,  ♻️ [REFACTOR]

#68 refactor:주석추가
  src/assets/main.css
  src/components/RegistrationModal.vue
  src/pages/Registration.vue
Labels: 🍑 해인,  ♻️ [REFACTOR]

#71 chore:사이브바수정
  .gitignore
  db.json
  index.html
  src/assets/main.css
  src/components/Registration/ModalMessage.vue
  src/components/Registration/RegistrationButton.vue
  src/components/common/Sidebar.vue
  src/pages/Home.vue
  src/stores/useOptionStore.js
  src/util/constants.js
Labels: 💟 [STYLE], 🛠️ [CHORE], 🍑 해인

#72 style:registration 페이지 좌우 margin 삭제
  src/components/Registration/AmountInput.vue
  src/components/Registration/CategorySelector.vue
  src/components/Registration/DateInput.vue
  src/components/Registration/MemoInput.vue
  src/components/Registration/PaymentMethodSelector.vue
  src/components/Registration/SourceInput.vue
  src/components/Registration/TimeInput.vue
  src/pages/Registration.vue
  src/pages/TransactionHistory.vue
Labels: 💟 [STYLE], 🍑 해인

#75 feat: vercel analytics 적용
  package-lock.json
  package.json
  src/App.vue
Labels: ⭐ [FEAT], 🍋 지민

#76 🎉 develop -> main merge
  .gitignore
  README.md
  db.json
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/assets/main.css
  src/components/Registration/AmountInput.vue
  src/components/Registration/CategorySelector.vue
  src/components/Registration/DateInput.vue
  src/components/Registration/MemoInput.vue
  src/components/Registration/ModalMessage.vue
  src/components/Registration/PaymentMethodSelector.vue
  src/components/Registration/RegistrationButton.vue
  src/components/Registration/SourceInput.vue
  src/components/Registration/TimeInput.vue
  src/components/common/Sidebar.vue
  src/pages/Home.vue
  src/pages/Registration.vue
  src/pages/TransactionHistory.vue
  src/stores/useOptionStore.js
  src/util/constants.js
Labels: ⭐ [FEAT], 🍊 경한, 💟 [STYLE], 🍋 지민, 🍇 소현, 🛠️ [CHORE], 🍑 해인,  ♻️ [REFACTOR]

#77 chore:api관련 수정
  src/pages/Registration.vue
Labels: 🛠️ [CHORE], 🍑 해인

#79 chore:오류 수정
  src/pages/Registration.vue
Labels: 🛠️ [CHORE], 🍑 해인
